version: "3"

services:
  database:
    image: postgres:14
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      APP_DB_USER: root
      APP_DB_PASS: root
      APP_DB_NAME: brighteyes
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  backend:
    image: brigh_eyes_backend
    build:
      context: ./bright-eyes-api
      dockerfile: Dockerfile
    environment:
      SERVER_LOG: false
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: root
      DB_PASS: root
      DB_NAME: brighteyes
      DB_SYNC: true
      DB_LOG: false
      JWT_SECRET: br1g8t3y3s
    depends_on: 
      - database
    links:
      - database
    ports:
      - "8080:80"

  frontend:
    image: brigh_eyes_frontend
    build:
      context: ./bright-eyes-ui
      dockerfile: Dockerfile
    depends_on:
      - database 
      - backend
    links:
      - backend
    ports:
      - "3000:80"